name: Foundry CI/CD
on:
  push:
    branches:
      - develop-foundry
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download library
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          
      - name: update bash Path
        run: source /home/runner/.bashrc

      - name: run foundry
        run: foundryup

      - name: Install dependencies
        run: forge install

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test